version: '3'

services:
  web:
    build: 
      context: . # path for searching of files
      dockerfile: Dockerfile.dev # docker file name that is used in building theimage
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # place holder
      - .:/app # referencing current folder to app folder inside container
  tests:
    build: 
      context: . # path for searching of files
      dockerfile: Dockerfile.dev # docker file name that is used in building theimage
    volumes:
      - /app/node_modules # place holder
      - .:/app # referencing current folder to app folder inside container
    command:
      ["npm", "run", "test"] # overriding the default command to be executed inthe container.
                             # Default command is mentioned in Dockerfile.dev
                             
